# Generated by Django 5.0.6 on 2024-05-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('course', models.CharField(choices=[('chs', 'Certificate in Health Science'), ('cat', 'Certificate in Applied Technology'), ('bit', 'Bachelor of Information Technology'), ('bbt', 'Bachelors in Business Technology'), ('mph', 'Master of Public Health')], max_length=100)),
                ('intake', models.CharField(choices=[('january', 'January Intake'), ('may', 'May Intake'), ('august', 'August Intake')], max_length=50)),
                ('entry_scheme', models.CharField(choices=[('alevel', 'A-Level certificate'), ('adult', 'Adult/Mature Learning'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('bachelors', 'Bachelors')], max_length=100)),
                ('sponsorship', models.CharField(choices=[('private', 'Private'), ('government', 'Government'), ('bursary', 'Bursary')], max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6)),
                ('date_of_birth', models.DateField()),
                ('residence', models.CharField(max_length=50)),
            ],
        ),
    ]
